name: build

permissions: read-all

on:
  workflow_call:
    inputs:
      go:
        description: Go version
        default: 1.17
        required: false
        type: string
      race:
        description: Enable Go race detector
        default: "-race"
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Install Go
        uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4 # v2.1.5
        with:
          go-version: ${{ inputs.go }}

      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Mod
        run: go mod download

      - name: Go Generate
        run: go generate ./... && git diff --exit-code

      - name: Go Build
        run: go build -v ./...

      - name: Go Test
        run: go test -v ${{ inputs.race }} -shuffle=on -coverprofile=coverage.txt ./...
